apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: collect-traces-
spec:
  entrypoint: slumps-distributed
  parallelism: 3
  arguments:
    parameters:
    - name: folder
    - name: main
  templates:
  - name: slumps-distributed
    steps:
    - - name: download-programs
        template: download-template
    - - name: execute-program
        template: verify-template
        arguments:
          parameters:
          - name: program
            value: "{{item}}"
        withParam: "{{steps.download-programs.outputs.parameters.programs}}"
        continueOn:
          failed: true
  - name: download-template
    script:
      image: madshansen/docker-git-ftp 
      command: [bash]
      source: |
        apt-get update
        apt-get install -y python wget unzip 

        echo "Copying only Wasm"
        mkdir -p /wasms
        for l in $(find /programs -type f)
        do
          HEADER="$(tr -d '\0'<$l | head -c 4 $l)"
          if [[ $HEADER  == "asm" ]]
          then
            cp $l /wasms/$(basename $l)
          fi
        done
        
        
        ls -l "/wasms" | wc -l 
        python -c "import json,os;  print(json.dumps(os.listdir('/wasms')))" > /out.txt 
        cat /out.txt
    outputs:
      parameters:
        - name: programs
          valueFrom: 
            path: "/out.txt"
    inputs:
      artifacts:
        - name: to_analyze
          path: /programs
          s3:
            bucket: my-bucket
            key: /babbage #{{workflow.parameters.folder}}
  - name: verify-template
    inputs:
      parameters:
        - name: program
      artifacts:
        - name: to_analyze
          path: /programs
          s3:
            bucket: my-bucket
            key: /babbage #{{workflow.parameters.folder}}
    outputs:
      artifacts:
        - name: logs
          path: /traces_{{workflow.name}}/{{inputs.parameters.program}}.swam.txt
          archive:
            # prevent compression
            none: { }
          s3:
            key: /traces_{{workflow.name}}/{{inputs.parameters.program}}.swam.txt
    #  - name: logs
    #    path: /slumps/crow/logs
    script:
      image: openjdk:11.0.7
      command: [bash]
      
      source: |
         mkdir -p /out
         mkdir -p /traces_{{workflow.name}}
         apt-get update && apt-get install -y python wget unzip 
         ls -l "/programs/babbage" 
         wget https://github.com/KTH/slumps/releases/download/0.01/swam.jar 
        
         java -jar swam.jar run --wasi -t /programs/babbage/{{inputs.parameters.program}} 2> /traces_{{workflow.name}}/{{inputs.parameters.program}}.swam.txt && ls /traces_{{workflow.name}}
        
      #resources:
      #  requests:
      #    memory: 2G
      #    cpu: 2
      #  limits:
      #    memory: 4G
      #    cpu: 4
