name: Build document to artifact
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latex
        run: sudo apt-get update && sudo apt-get install -y texlive-full git wget jq
      - name: Build document
        run: pdflatex -interaction=nonstopmode Lic.tex && ls .
      - name: Archive pdf artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Lic.pdf
          path: ./Lic.pdf

      - name: Cloning mysite
        run: git clone https://github.com/Jacarte/jacarte.github.io.git

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/analyzer
          asset_name: analyzer
          tag: ${{ github.ref }}
          overwrite: true
          body: "Analyzer binary for linux"