name: Build document to artifact
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jacarte/latex-build:latest25
      credentials:
        username: jacarte
        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build document
        run: |
          pdflatex -interaction=nonstopmode -shell-escape Lic.tex && bibtex Lic && pdflatex -shell-escape -interaction=nonstopmode Lic.tex
          
      # If the build works, do the spell check

      - name: Spell check
        run: |
          
      - name: Archive pdf artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Lic.pdf
          path: ./Lic.pdf

      - name: Split by chapter
        run: |
          mkdir chapters 
          python3 /tools/split_document.py Lic.pdf chapters && ls chapters

      - name: Spell checking report
        run: |
          python3 /tools/get_latex_pieces.py .
        env:
          EXCLUDE: "['llvm_code_blocks.tex', 'overlaping_explain.tex', 'table_template copy.tex', 'table_template copy 2.tex', 'table_template.tex', 'old.tex', 'same_instruction.tex', 'example.tex' ,  'generation table_template.tex', 'summary_swedish.tex']"

      - name: Archive spell report
        uses: actions/upload-artifact@v1
        with:
          name: report.json
          path: report.json
      
      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"


      - name: Annotate new pdf on a new branch
        run: |
          git config --global --add safe.directory /__w/KTH-Licentiate-Thesis/KTH-Licentiate-Thesis
          python3 /tools/annotate_tex.py report.json dico.text $(git log -n 1 --pretty=%H) $(git config --get remote.origin.url) 2> count.txt

          cat count.txt
          
          # cp /tools/*.md .

          git rm -rf . && git checkout -b reports
          git add *.md report.json && git commit -m 'Spell check report' 
          git push origin reports --force

          if [ $(cat count.txt) -gt $THRESHOLD ]
          then
            echo "Number of warnings above the threshold: $(cat count.txt)"
            exit 1
          fi

        env:
          THRESHOLD: 200000

      - name: Deploy document
        run: |
          
          mkdir /chapters
          
          cp chapters/*.pdf /chapters
          ls /chapters
          cp Lic.pdf /Lic.pdf

          cd /
          git clone https://${{secrets.REPO_KEY2}}@github.com/Jacarte/jacarte.github.io jacartepage
          cd jacartepage
          cp /Lic.pdf assets/pdf/thesis/Lic.pdf
          cp -r /chapters/* assets/pdf/thesis

          git config --global user.email "xppcoder@gmail.com"
          git config --global user.name "jacarte"
          git config --global credential.helper cache

          git add .
          git commit -m "Automatic deploy from thesis repo"
          git push

          # The action on the page will automatically deploy the documents
        env:
          REPO_KEY: '${{ secrets.REPO_KEY2 }}'