name: Build document to artifact
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jacarte/latex-build:latest2
      credentials:
        username: jacarte
        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build document
        run: pdflatex -interaction=nonstopmode -shell-escape Lic.tex && bibtex Lic && pdflatex -shell-escape -interaction=nonstopmode Lic.tex && ls .

      # If the build works, do the spell check

      - name: Spell check
        run: |
          
      - name: Archive pdf artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Lic.pdf
          path: ./Lic.pdf

      - name: Split by chapter
        run: |
          mkdir chapters 
          python3 /tools/split_document.py Lic.pdf chapters && ls chapters

      
      - name: Archive pdf chapters
        uses: actions/upload-artifact@v1
        with:
          name: chapters
          path: ./chapters

      - name: Spell checking report
        run: |
          python3 /tools/get_latex_pieces.py .

      - name: Archive spell report
        uses: actions/upload-artifact@v1
        with:
          name: report.json
          path: report.json
      
      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"


      - name: Annotate new pdf on a new branch
        run: |
          git config --global --add safe.directory /__w/KTH-Licentiate-Thesis/KTH-Licentiate-Thesis
          git branch spell2pdf
          python3 /tools/annotate_tex.py report.json dico.text > report.logs

      - name: GIT
        run: |
          git rm -rf . && git checkout -b reports
          git add report.logs report.json && git commit -m 'Spell check report' 

      - name: GIT
        run: git push origin reports --force

      # Last step, publish the thesin in my personal webpage

      #- name: Cloning mysite
      #  run: git clone https://github.com/Jacarte/jacarte.github.io.git
      #- name: Uploading compiled to mysite
      #  run: |
      #   cp Lic.pdf jacarte.github.io/assets/pdf/Lic.pdf 
      #   cd jacarte.github.io
         
      #   git config --global user.name "github-actions[bot]"
      #   git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      #   git add assets/pdf/Lic.pdf && git commit -m "Updating Lic document"
         
      #   git push https://$USERNAME:$REPO_KEY@github.com/Jacarte/jacarte.github.io.git
         
      #  env:
      #    REPO_KEY: ${{secrets.REPO_KEY}}
      #    USERNAME: github-actions[bot]